### ISSUE TITLE
Comparing with uncertainty learning

### ISSUE THREAD

**Issue by ShenhanQian** [Jeff-sjtu/res-loglikelihood-regression#14]
Hi, thanks for your amazing work! 
I am curious about whether you have compared your method with uncertainty learning qunatitatively?

![image](https://user-images.githubusercontent.com/23174052/131995338-641bec9d-6dec-4aa1-8b73-f2c97bbd73f7.png)

**Comment by jeffffffli** [comment]
Hi @ShenhanQian,

In Table 7 of the paper, we compare our method with different assumptions of the distribution. In the 3rd and the 4th line in Table 7, the Gaussian and Laplace distributions are represented with learnable `mu` and `sigma`, which are exactly the same as the conventional uncertainty.

**Comment by ShenhanQian** [comment]
This resolves my concern. Sorry for missing it, and thank you!
