### ISSUE TITLE
Quesion about NUM_FC_FILTERS set by -1

### ISSUE THREAD

**Issue by ChengBinJin** [Jeff-sjtu/res-loglikelihood-regression#17]
@Jeff-sjtu 
Hi, thank you for your great work! Recently, I study your code, and I found that NUM_FC_FILTERS is set to -1 in YAML file. It will cause the function is the identity mapping. Is it correct?
![image](https://user-images.githubusercontent.com/37034031/133619075-e931153e-9637-4fb4-8182-b35f14038e8a.png)

**Comment by jeffffffli** [comment]
Hi @ChengBinJin, it is correct. We set `NUM_FC_FILTERS=0` and only use one final FC layer for regression.

**Comment by ChengBinJin** [comment]
I see, thank you!
