### ISSUE TITLE
when will you release the 3d version and the minimal implementation?

### ISSUE THREAD

**Issue by 674106399** [Jeff-sjtu/res-loglikelihood-regression#2]
Hello, thank you for sharing your awesome work. 
Could you tell me when will you guys release the 3d version and  the minimal implementation?

**Comment by Guocode** [comment]
I am also looking forward to 3D version, I think it should be easy to expand to 3D but I failed to reach that. Flow splits the input to two stream, so it's very suitable for 2D.

**Comment by Jeff-sjtu** [comment]
Hi @674106399 and @Guocode,

We will release the 3D version in two days! (I hope it can be finished tomorrow). Thank you for your interest ;)

**Comment by 674106399** [comment]
> Hi @674106399 and @Guocode,
> 
> We will release the 3D version in two days! (I hope it can be finished tomorrow). Thank you for your interest ;)

That would be great! Thanks again~
Best

**Comment by Jeff-sjtu** [comment]
Hi @674106399 and @Guocode ,

The 3D version is released. If the training code has any bugs, please feel free to post issues.

**Comment by ChenyanWu** [comment]
Thanks for your great work!
Could you provide the code about preprocessing HM36 dataset and how to generate the annotation JSON file?

**Comment by Jeff-sjtu** [comment]
Hi @ChenyanWu,

The usage of H36M data and JSON files will be updated soon. We use the data parsed by [PoseNet](https://github.com/mks0601/3DMPPE_POSENET_RELEASE).

**Comment by 674106399** [comment]
Hi @Jeff-sjtu ,
I got this error during training:
"ValueError: The value argument must be within the support"
from this line:
log_phi_3d = self.flow3d.log_prob(bar_mu_3d)

then I passed validate_args=False to the MultivariateNormal follow https://github.com/pytorch/pytorch/issues/59228
but the loss become nan after several step, do you have any idea about this?

I'm using pytorch 1.8 cuda 11.2

**Comment by Jeff-sjtu** [comment]
I think this error comes from the PyTorch version. I test the training code with Pytorch `1.1.0` and `1.5.0`. These two versions run successfully. Our initial results reported in the paper is run with `1.1.0`.

**Comment by 674106399** [comment]
> I think this error comes from the PyTorch version. I test the training code with Pytorch `1.1.0` and `1.5.0`. These two versions run successfully. Our initial results reported in the paper is run with `1.1.0`.

this error occurs when bar_mu is negative(log_prob expects positive input):
`
bar_mu = (pred_jts - gt_uvd) / sigma  # use torch.abs ?
bar_mu = bar_mu.reshape(-1, 3)
bar_mu_3d = bar_mu[gt_3d_mask > 0]
bar_mu_2d = bar_mu[gt_3d_mask < 1][:, :2]
# (B, K, 3)
log_phi_3d = self.flow3d.log_prob(bar_mu_3d)
log_phi_2d = self.flow2d.log_prob(bar_mu_2d)`

how about change into
bar_mu = torch.abs(pred_jts - gt_uvd) / sigma

**Comment by Jeff-sjtu** [comment]
The value of `bar_mu` can be both positive and negative. The input of `log_prob` does not expect to be positive. Did you run the code with a lower version of PyTorch? Such as `1.5.0`. I will try to figure out what is problem in `1.8.0` later.

**Comment by 674106399** [comment]
Are target coords must be normalized into (0, 1)? I'm training with my own project, and I transform the pred_jts into input scale to calculate loss with target coords. Could it cause any error?

**Comment by 674106399** [comment]
Sorry for asking such a stupid question.. I fixed it by normalizing the inputs. Thanks a lot for your patient help :)

**Comment by Jeff-sjtu** [comment]
Hi @674106399, glad to see you got the problem solved.

Yes, in our implementation, the coordinate is normalized into (-0.5, 0.5). Since we use `sigmoid` to make the predicted `sigma` positive, to ensure the scale of `sigma` can cover most cases, the coordinate should be normalized. The `softplus` operation (mentioned by #4) can predict a larger scale of `sigma`. But I think a proper normalization is still necessary.
