### ISSUE TITLE
A question about self.fcs

### ISSUE THREAD

**Issue by Tau-J** [Jeff-sjtu/res-loglikelihood-regression#27]
Hello, I just notice that you create a self.fcs in both 2d and 3d models, but it seems that it isn't used in anywhere

from regression_nf_3d.py line 92:
self.fcs, out_channel = self._make_fc_layer()

Could you tell me why does it exist?

**Comment by jeffffffli** [comment]
Hi @674106399 , `self.fcs` is not used because we found using only one FC layer is good enough. You can directly delete it and it won't affect the final results.
