### ISSUE TITLE
训练第一个epoch的loss变成负数

### ISSUE THREAD

**Issue by cv-nlp** [Jeff-sjtu/res-loglikelihood-regression#33]
loss: -8.48068483 | acc: 0.2207:  71%|█████████████████████▎        | 417/586 [47:52<27:15,  9.68s/it]

**Comment by liza-li** [comment]
同样问题，请问解决了吗？

**Comment by jeffffffli** [comment]
@liza-li @cv-nlp , 这是正常现象，请参考#5
