### ISSUE TITLE
can't reproduce the result present in the paper

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [Jeff-sjtu/res-loglikelihood-regression#38]
hi @Jeff-sjtu 
i use the cmd `./scripts/train.sh ./configs/256x192_res50_regress-flow.yaml train_rle_coco` to reproduce the result present in the paper, but only get `##### Epoch 255 | gt mAP: 0.7123198166036238 | det mAP: 0.6962231312113063 #####`, lower than the released model you provide where `gt box: 0.7218652898214926 mAP | det box: 0.7127219006071578 mAP`. can u give the complete training pipeline to reproduce the result?
thanks

**Comment by zimenglan-sysu-512** [comment]
btw, i use two GPUs to train.

**Comment by zimenglan-sysu-512** [comment]
hi @Jeff-sjtu 
now i can reproduce the result present in the paper, 
- train a heatmap based model, which get `4 GPUs ==> Epoch 139/140 | gt mAP: 0.7253/0.7264/111 | det mAP: 0.7101/0.7101/121`
- use the trained model to finetune rlepose, and get `Test Epoch 255/270 | gt mAP: 0.7257/0.7267/227 | det mAP: 0.7128/0.7131/219`

**Comment by markkim1115** [comment]
Hello, small curiosity, can you share what the problem was???

**Comment by zimenglan-sysu-512** [comment]
hi @markkim1115 
directly train rle, can't get the results from released model. so you should pretrain a heatmap-based model.

**Comment by Jackqu** [comment]
hi， which heatmap-based model  does you use ? @zimenglan-sysu-512
