### ISSUE TITLE
Implementation of logQ

### ISSUE THREAD

**Issue by Indigo6** [Jeff-sjtu/res-loglikelihood-regression#41]
https://github.com/Jeff-sjtu/res-loglikelihood-regression/blob/203dc3195ee5a11ed6f47c066ffdb83247511359/rlepose/models/criterion.py#L37
Sorry for bothering you, I wonder if I'm right thinking the above line misimplemented the loss from $logQ(\bar\mu)$ in the paper to $logQ(\mu)$？

**Comment by jeffffffli** [comment]
Sorry, I don't quite understand your question.

**Comment by Indigo6** [comment]
Thank you for your reply and sorry for the missing details.
In your paper,    
   $$
   -logP(\mu)=-logP(\bar\mu)+log\ \hat\sigma
   $$
   $$
   log_\phi P(\bar\mu) = logQ(\bar\mu)+log_\phi G(\bar\mu) + log s
   $$
where $\bar\mu$ is $\frac{\mu-\hat\mu}{\hat\sigma}$. Therefore, I think $logQ(\bar\mu)$ should not has the $log\hat\sigma$ term. In my perspective, the implementation in the code seems to be:
   $$
   -logP(\mu)=-logP(\bar\mu)-logQ(\mu)+log\ \hat\sigma
   $$
   $$
   log_\phi P(\bar\mu) = log_\phi G(\bar\mu) + log s
   $$

**Comment by Jeff-sjtu** [comment]
I think you have some misunderstanding here. Let's say Q(x) is a gaussian distribution. Q(x) = 1/(2pi * sigma) * exp( -0.5 * x^2 / sigma^2 ). Thus log Q(\bar\mu) = -log sigma - 0.5 * (gt_uv - pred_jts) ^2 / sigma. Laplace distribution has the similar implementation.

**Comment by Indigo6** [comment]
Corrections: "is irrelevant to $\hat\sigma$" -> "should not has the $log\hat\sigma$ term"

**Comment by jeffffffli** [comment]
Hi @Indigo6, I checked the code and found you are correct. But I re-run the experiment and found the current implementation obtains better performance. I am trying to figure out why.

**Comment by Indigo6** [comment]
Thanks for your reply!
I found this problem when implementing your method to MMPose. The reviewer asked about the double $log\hat\sigma$ and I opened this issue to check if my explanations were right. 
Also, I got the same performance degradation after removing the $log\hat\sigma$ in $logQ(\bar\mu)$, and the implementation in MMPose retains it.
