### ISSUE TITLE
negative loss val problem

### ISSUE THREAD

**Issue by ssssholmes** [Jeff-sjtu/res-loglikelihood-regression#5]
Thanks for the great work! I run the code and find sometimes the loss value becomes negative. Is it normal?

**Comment by ssssholmes** [comment]
![屏幕快照 2021-08-07 13 43 14](https://user-images.githubusercontent.com/48430696/128589528-270ff4ab-bc15-49df-bf22-30ce34bf0858.png)

**Comment by Jeff-sjtu** [comment]
Hi @ssssholmes, the loss value can be negative. Since `L=-log p`, if the `p>1`, the loss will be negative.

**Comment by ssssholmes** [comment]
Got it! Thank you! @Jeff-sjtu
